### ISSUE TITLE
Check results, warnings e notes.

### ISSUE THREAD

**Issue by cavalcanti1985** [ipeadata-lab/ipeaplot#11]
Para registro, @PedroJorge7:

<img width="567" alt="image" src="https://github.com/ipeadata-lab/ipeaplot/assets/52927575/dda2919c-9033-44b8-a9c8-cbdb7d90e98d">

**Comment by PedroJorge7** [comment]
Após uma nova rodada de ajuste e teste, resolvi o warning e as duas notes
![image](https://github.com/ipeadata-lab/ipeaplot/assets/52927575/52dce83d-ee39-4c8f-8e17-0ab6cfcc755e)
