### ISSUE TITLE
vline and hline as parameters?

### ISSUE THREAD

**Issue by rafapereirabr** [ipeadata-lab/ipeaplot#14]
In the `ggplot2` grammar, there is a there are geoms to add horizontal and vertical lines (`geom_hline()` and `geom_vline()`).

I see that the current version of the package includes `vline` and `hline` as parameters of `scale_color_ipea()` and  `scale_fill_ipea()`. Imho, this doesn't make sense. The `scale_*_ipea()` should only relate to color palettes and legends. The vertical and horizontal lines we add to plots are not related to those.

I would suggest remove these two parameters.

**Comment by PedroJorge7** [comment]
Como sugerido, eu removi os argumentos da função.
