### ISSUE TITLE
Parameter `direction` in scale_*_ipea()`

### ISSUE THREAD

**Issue by rafapereirabr** [ipeadata-lab/ipeaplot#16]
The parameter `direction` is commontly used in `{ggplot2}` to indicate the direction of the color scale.  See for example `?scale_colour_viridis_d()`. In fact, we this parameter in the `ipeaplot::ipea_pal()` function.

However, `ipeaplot::scale_*_ipea()` also uses the same parameter name to refer to what we refer to as `legend.direction` in `{ggplot2}`. This creastes confusion and potential conflicts.

I would suggest we change the name the `direction` parameter to `legend.direction`.

**Comment by PedroJorge7** [comment]
Eu concordo. Vou fazer a modificação no pacote.
