### ISSUE TITLE
Undocumented arguments in theme_ipea()

### ISSUE THREAD

**Issue by rafapereirabr** [ipeadata-lab/ipeaplot#17]
>   Undocumented arguments in documentation object 'theme_ipea'
    'x' 'y' 'yend' 'xend' 'x_breaks' 'y_breaks' 'bar_adjust' 'angle'
    'adjust_ticks'

**Comment by PedroJorge7** [comment]
Fiz a inclusão desses argumentos no pacote

**Comment by PedroJorge7** [comment]
Os argumentos 'x' 'y' 'yend' 'xend' e 'bar_adjust' foram removidos, enquanto o 'x_breaks' e 'y_breaks' foram ajustados e 'angle' foi renomeado
