### ISSUE TITLE
pie.adjust

### ISSUE THREAD

**Issue by cavalcanti1985** [ipeadata-lab/ipeaplot#22]
Existe alguma forma de automatizar as configurações do atributo `pie.adjust` sempre que o tipo de gráfico for de pizza?

**Comment by PedroJorge7** [comment]
Eu acredito que não, mas vou procurar um pouco melhor

**Comment by rafapereirabr** [comment]
A gente pode não ter o "pie.adjust" como forma sutil de desencorajar as pessoas a fazerem grafico de pizza ? :) Falo serio.

**Comment by PedroJorge7** [comment]
Eu tbm não curto a ideia de fazer gráfico de pizza. Eu criei o argumento porque estava no editorial. Se vocês forem a favor eu posso tirar o argumento e colocar o ajuste manual apenas para ter no cookbook

**Comment by PedroJorge7** [comment]
Então tiramos esse comparativo do pie plot? Não vão estranhar né? Porque vai ficar gráfico 1, gráfico 3, 4, 5....

**Comment by rafapereirabr** [comment]
otimo

**Comment by PedroJorge7** [comment]
Removi o argumento pie.adjust e reordenei a numeração do cookbook
