### ISSUE TITLE
Atualização das figuras do cookbook

### ISSUE THREAD

**Issue by cavalcanti1985** [ipeadata-lab/ipeaplot#43]
@PedroJorge7: 
- Por favor, revise as figuras do cookbook, elas não estão refletindo as últimas mudanças no código. 
- Além daqueles apontados pelo Fabio, o gráfico 4 também tem algumas pequenas diferenças. Na posição de y = 0, por exemplo.
- No código do gráfico 5, trocar `size` pelo atributo `linewidth` para evitarmos problemas em novas versões do ggplot2.

_Originally posted by @cavalcanti1985 in https://github.com/ipeadata-lab/ipeaplot/issues/41#issuecomment-1991462738_

**Comment by PedroJorge7** [comment]
Olá @cavalcanti1985 refiz o trabalho de revisar as figuras do cookbook. Também fiz a mudança do argumento  ```geom_line(size=1)``` por ```geom_line(linewidth=1)```

O gráfico 4 ficou assim
![image](https://github.com/ipeadata-lab/ipeaplot/assets/52927575/ed2747cd-e407-438c-ae49-873d1e5b75d2)

**Comment by palmaresk8** [comment]
Tudo parece ok agora, exceto o Gráfico 2 que está com os labels levemente desalinhados (não sei se são os labels ou se são os "rugs" que estão desalinhados).
![Grafico_2](https://github.com/ipeadata-lab/ipeaplot/assets/6098533/c57a3041-1a10-4e7d-976b-edab74d40cd4)
