### ISSUE TITLE
Reunião: encaminhamentos

### ISSUE THREAD

**Issue by cavalcanti1985** [ipeadata-lab/ipeaplot#5]
Encaminhamentos:
- [x] Revalidar fontes, cores e eps com o Editorial (Pedro Cavalcanti);
- [x] Theme_ipea apenas com padrões gráficos (sem escala de cores) (Pedro Jorge);
- [x] Escalas de cores nos formatos scale_color e scale_fill (discreta e contínua como argumentos). Criar escala contínua e novas cores discretas a partir da paleta Ipea1 (Pedro Jorge).
- [x] Nome do pacote:  ipeaplot (Pedro Cavalcanti);
- [x] Criar script de validação com varios graficos (Pedro Jorge e Cavalcanti).

**Comment by rafapereirabr** [comment]
Oi pessoal, qual é o script de validação com varios graficos?
