### ISSUE TITLE
Ajustes em theme_ipea

### ISSUE THREAD

**Issue by cavalcanti1985** [ipeadata-lab/ipeaplot#6]
- [x] Fontes (Frutiger)
- [x] Linhas de grid verticais quando as barras forem horizontais
- [x] Espaço entre ícones e textos na legenda (1mm)
- [x] Tamanho dos ícones das legendas
- [x] Espaços entre eixos, rótulos e legendas (gráfico 9 do manual do editorial)

**Comment by PedroJorge7** [comment]
Pedro, levantar aqui alguns pontos do código em que tento ajustar cada tópico apontado

- Fonte de textos internos e legendas (Frutiger-LT-55)

Acredito que com ```ggplot2::theme_gray(base_family` = "Frutiger LT 55 Roman")```  Consiga generalizar para todo o ggplot2 um padrão. Ai titulo e subtítulo faço manualmente

 ```
    # Adjusts the vertical alignment of the y-axis title
    axis.title.y = ggplot2::element_text(family = "Frutiger LT 47 LightCn",vjust = 1.5, size = 8, lineheight = 9.6),
    # Adjusts the vertical alignment of the x-axis title
    axis.title.x = ggplot2::element_text(family = "Frutiger LT 47 LightCn",vjust = -0.4, size = 8, lineheight = 9.6),
    # Sets the appearance of the plot title
    plot.title = ggplot2::element_text(
      # FullName (Frutiger LT 47 Light Condensed). FamillyName (Frutiger LT 47 LightCn)
      family = "Frutiger LT 47 LightCn",
      size = 10, lineheight = 12, hjust = 0,
      margin = margin(0,0,0,0, unit = 'mm')
    ),
    # Sets the appearance of the plot subtitle
    plot.subtitle = ggplot2::element_text(
      # FullName (Frutiger LT Std 57 Condensed). FamillyName (Frutiger LT Std)
      family = "Frutiger LT Std",
      size = 9, lineheight = 10.8, face = "bold", hjust = 0,
      margin = margin(0,0,3,0, unit = 'mm'),
    ),
 ```

- Espaço entre ícones e textos na legenda (1mm)

 ```
    # Set horizontal and vertical spacing between legend keys (2 right,2 bottom,1 left)
    legend.spacing = margin(0,2,2,1, unit = 'mm'),
 ```

- Tamanho dos ícones das legendas

Aqui ainda fiquei com uma dúvida, pois o editorial pede para mudar o ícone do quadrado e da linha, mas parece que o theme só tem a opção para mudar um

 ```
    #change legend key size
    #legend.key.size = unit(2, 'mm'),
    # Set key size
    legend.key.size = unit(5,"mm","line"),
 ```

Se rodar os dois juntos fica com erro

- Espaços entre eixos, rótulos e legendas (gráfico 9 do manual do editorial)

 ```
    # Adjust haste length
    axis.ticks.length = unit(2, "mm"),
    # Set horizontal and vertical spacing between legend keys (2 right,2 bottom,1 left)
    legend.spacing = margin(0,2,2,1, unit = 'mm'),
    # Spacing between faceted plots
    panel.spacing = unit(4, "mm"),
    # Set Margin spacing
    legend.margin= margin(t= unit(3, 'mm')),
 ```

**Comment by PedroJorge7** [comment]
Fiz um pequeno ajuste. Veja se os warnings persistem

**Comment by rafapereirabr** [comment]
@cavalcanti1985 , voce poderia por favor compartilhar aqui o codigo usado para gerar / reproduzir o grafico ?
