### ISSUE TITLE
erro na vignette: could not find function "scale_color_continuous_ipea"

### ISSUE THREAD

**Issue by rafapereirabr** [ipeadata-lab/ipeaplot#8]
Rodando a linha abaixo para checar o pacote.
`devtools::check(pkg = ".",  cran = FALSE, env_vars = c(NOT_CRAN = "true"))`

Aparece o seguinte erro:

```
─  installing the package to build vignettes
E  creating vignettes (42.3s)
   --- re-building 'intro_ipeaplot.Rmd' using rmarkdown
   
   Quitting from lines 60-76 [unnamed-chunk-5] (intro_ipeaplot.Rmd)
   Error: processing vignette 'intro_ipeaplot.Rmd' failed with diagnostics:
   could not find function "scale_color_continuous_ipea"
   --- failed re-building 'intro_ipeaplot.Rmd'
   
   SUMMARY: processing the following file failed:
     'intro_ipeaplot.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'Rcmd.exe' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Type .Last.error to see the more details.
```

**Comment by PedroJorge7** [comment]
Fiz uma atualização das vinhetas e ajustes em outros arquivos. Também realizei o teste indicado pelo Rafael. O output que tive foi:

<img width="567" alt="image" src="https://github.com/ipeadata-lab/ipeaplot/assets/52927575/dda2919c-9033-44b8-a9c8-cbdb7d90e98d">

Aparentemente o problema de erro em relação a vinheta foi resolvido, mas depois preciso resolver os warning e notes.

**Comment by rafapereirabr** [comment]
ótimo. Entao ja pode fechar esse issue! 

ps. ainda tem que resolver aquela questão do **purrr**, **sysfonts** e **geobr**. Mas isso fica para outro issue.
